#!/bin/bash

ConfigFile="config.yml"
CurentDir="$(pwd)"
TempDir="/temp/.NAiSweb"

##########

function exit_error() {
  cd "${CurentDir}/"; rm -Rf "${TempDir}"
  exit 1
}

function ctrl_c() {
  echo ""; echo "! execution interrupted !"; echo ""
  exit_error
}

function check_prereq() {
  if [ ! -f "./bin/yaml2json" ] ; then echo "yaml2json is not present"; exit_error ; fi
  if ! jq --version > /dev/null 2>&1 ; then echo -e "jq is not installed\n try : \nsudo apt-get install jq"; exit_error ; fi
}

# Main
PATH="${PATH};${CurentDir}/bin"

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

# prerequisite checks
check_prereq


echo ""
cd "${CurentDir}/"; rm -Rf "${TempDir}"
exit 0
